#!/bin/bash 

if [[ $1 == "-u" ]];then
        python3 ~/tools/scripts/update_check.py
elif [[ $1 == "-v" ]];then
        python3 ~/tools/scripts/version_check.py
else
        echo "parameter error"
        echo "-u 更新版本
-v 查询版本"

fi
