#!/bin/bash
echo "请确定你输入的文件路径在/home/$USER/qpilot_dev_ws/下 ！！！！！！！！"
read -p "输入日志文件名如：TJ_IGV_23_2022-05-14-1621_log_bag.tar.gz：" log_bag_name
if [ -f /home/$USER/qpilot_dev_ws/${log_bag_name} ];then
  cd /home/qomolo/qpilot_dev_ws/
  folder_name=`basename ${log_bag_name} .tar.gz`
  echo ${folder_name}
  sudo tar -zxf /home/$USER/qpilot_dev_ws/${log_bag_name} ${folder_name}/lidar -C /home/$USER/qpilot_dev_ws/
  #echo "检测到了以下点云包文件夹:"
  result=`ls /home/$USER/qpilot_dev_ws/${folder_name}/lidar`
  #echo $result
  read -p "请输入问题发生的时间前的时刻【按照格式：20220522011140】：" start_time
  play_folder=/home/$USER/qpilot_dev_ws/${folder_name}/lidar
  sudo sed -i "18c \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ {'lidar_path': '/debug/${folder_name}/lidar'}," /opt/qomolo/igv-sensor/share/cloud2map_viewer/launch/map_pointcloud.launch.py
  if [[ ${#start_time} != 14 ]];then
    echo "时间格式不对，无法执行，请按照格式来输入如20220522011140"
    exit 0
  fi
  sudo sed -i "17c \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ {'start_time': '${start_time}'}," /opt/qomolo/igv-sensor/share/cloud2map_viewer/launch/map_pointcloud.launch.py
  qomolo_robot_id=tj0${log_bag_name:7:2}
  docker exec -it second bash -c "export QOMOLO_ROBOT_ID=$qomolo_robot_id && source /opt/qomolo/igv-sensor/setup.bash && ros2 launch cloud2map_viewer map_pointcloud.launch.py"
else
  echo "您输入的路径有误"
fi

