#!/bin/bash

clear
cd ~
curl http://vpn.qomolo.com:8080/status.log -o vpn-gatewayIP &> /dev/null

if [[ $1 == "" ]];then
	echo "not parameter"
fi

case $1 in
$1)
        cat vpn-gatewayIP | grep "$1" --color=auto | awk -F ',' '{print $1,$2}' | awk '/^1/{print}'
;;
esac
rm -rf vpn-gatewayIP
