#!/bin/bash 

if [[ $1 == "-u" ]];then
	if [[ $2 == "" ]];then
		echo "igv -u + 固件
举例：igv -u qpilot-setup"
	else
		python3 ~/tools/test.py $2
	fi
elif [[ $1 == "-v" ]];then
	echo "开始查询版本"
	python3 ~/tools/version_check.py
elif [[ $1 == "-r" ]];then
	echo "注意！！，这将会重启docker"
	python3 ~/tools/reboot_igv.py
else
	echo "parameter error"
        echo "-u 更新版本
-v 查询版本
-r 重启docker"

fi
