
CXX = g++
SRC = scripts.cpp function_implementation.cpp 
EXECUTABEL = scripts test
CMD = -o

scripts:scripts.cpp
	@${CXX} ${SRC} ${CMD} scripts

test:test.cpp
	@${CXX}] test.cpp {CMD} test


cl:
	@rm -r ${EXECUTABEL}