
CXX = g++
FILE = staff_management.cpp workermanage.cpp staff.cpp manager.cpp boss.cpp
EXECTABLE = out
CMD = -o
ARCIVE_FILE = *.txt

${EXECTABLE}:${FILE}
	@${CXX} ${FILE} ${CMD} ${EXECTABLE} 

cl:
	@rm -r ${EXECTABLE} ${ARCIVE_FILE}