
CXX = g++
FILE = staff_management.cpp workermanage.cpp staff.cpp manager.cpp boss.cpp
EXECTABLE = out
CMD = -o

${EXECTABLE}:${FILE}
	@${CXX} ${FILE} ${CMD} ${EXECTABLE} 

clean:
	@rm -r ${EXECTABLE}